import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Training Certificate System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  form,
  discard,
  certification,
  signout,
}: Readonly<{
  children: React.ReactNode;
  form: React.ReactNode;
  discard: React.ReactNode;
  certification: React.ReactNode;
  signout: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {form}
        {discard}
        {certification}
        {signout}
      </body>
    </html>
  );
}
